### ISSUE TITLE
AwilixTypeError

### ISSUE THREAD

**Issue by pointer** [jeffijoe/awilix#134]
AwilixTypeError: build: expected targetOrResolver to be a function or class, but got mydataSerializer.
    at Function.assert (C:\_dev\sgdtserver\node_modules\awilix\lib\errors.js:83:19)
    at Object.build (C:\_dev\sgdtserver\node_modules\awilix\lib\container.js:312:34)
    at middlewareFactoryHandler (C:\_dev\sgdtserver\node_modules\awilix-express\lib\invokers.js:106:34)
    at Layer.handle [as handle_request] (C:\_dev\sgdtserver\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\_dev\sgdtserver\node_modules\express\lib\router\index.js:317:13)
    at C:\_dev\sgdtserver\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\_dev\sgdtserver\node_modules\express\lib\router\index.js:335:12)
    at next (C:\_dev\sgdtserver\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\_dev\sgdtserver\node_modules\express\lib\router\index.js:174:3)
    at router (C:\_dev\sgdtserver\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\_dev\sgdtserver\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\_dev\sgdtserver\node_modules\express\lib\router\index.js:317:13)
    at C:\_dev\sgdtserver\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\_dev\sgdtserver\node_modules\express\lib\router\index.js:335:12)
    at next (C:\_dev\sgdtserver\node_modules\express\lib\router\index.js:275:10)
    at scopePerRequestMiddleware (C:\_dev\sgdtserver\node_modules\awilix-express\lib\scope-per-request.js:13:16)

**Comment by jeffijoe** [comment]
Need to see what `mydataSerializer` is.

**Comment by pointer** [comment]
Here it is ....
const MydataSerializer = {
  serialize({ id, data }) {
    return {
      id,
      data
    };
  }
};

module.exports = MydataSerializer;

**Comment by jeffijoe** [comment]
How are you registering it? And how are you resolving it? I see you're using Awilix Express, can you show me the controller/route handler that you use this with?

**Comment by pointer** [comment]
// Serializers
container.register({
  mydataSerializer: asValue(MydataSerializer)
});
///////
const { Router } = require("express");
const { inject } = require("awilix-express");
const Status = require("http-status");

const MydatasController = {
  get router() {
    const router = Router();

    router.use(inject("mydataSerializer"));
...
}
usage ....
  index(req, res, next) {
    const { getAllMydatas, mydataSerializer } = req;
    const { SUCCESS, ERROR } = getAllMydatas.outputs;

    getAllMydatas
      .on(SUCCESS, mydatas => {
        res.status(Status.OK).json(mydatas.map(mydataSerializer.serialize));
      })
      .on(ERROR, next);

    getAllMydatas.execute();
  },
 route....
  apiRouter.use("/mydatas", controller("mydata/MydatasController"));

**Comment by jeffijoe** [comment]
You are using `inject` wrong. Please see [the docs](https://github.com/talyssonoc/awilix-express#api).

**Comment by pointer** [comment]
Thanks buddy.....
