### ISSUE TITLE
awilix.loadModules not resolving when process is not started from the root folder

### ISSUE THREAD

**Issue by rqyrku** [jeffijoe/awilix#149]
Steps to reproduce: 
1. Clone this test repo and install deps: https://github.com/rqyrku/awilix-resolver-issue
2. Init the process from the root folder `node server/index.js`

Result: 

> AwilixResolutionError: Could not resolve 'fastify'.

> Resolution path: fastify
    at resolve (/home/reidi/Projects/test/node_modules/awilix/lib/container.js:234:23)
    at Object.get (/home/reidi/Projects/test/node_modules/awilix/lib/container.js:65:32)
    at start (/home/reidi/Projects/test/server/index.js:5:25)
    at Object.<anonymous> (/home/reidi/Projects/test/server/index.js:20:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)

Difference:
1. Start the process inside the server folder: `cd server & node index.js`

Result: 

> [AwilixContainer (registrations: 4)]
> {"level":30,"time":1571015961583,"msg":"Server listening at http://0.0.0.0:8000","v":1}
> [FASTIFY] Listening on: http://0.0.0.0:8000

**Comment by jeffijoe** [comment]
You can set up `cwd` in `loadModules`. See [the docs](https://github.com/jeffijoe/awilix#containerloadmodules). 😄 s
