### ISSUE TITLE
Bug: Not beign able to resolve dependency properly

### ISSUE THREAD

**Issue by VIMGAS** [jeffijoe/awilix#150]
I am trying to resolve a dependency but when I do it the normal way, I get an error.

```js
Container.resolve('AccountIndexValidator');
```
Outputs:
```
TypeError: Cannot read property 'AccountIndexValidator' of null
    at Object.resolve (P:\Coobo\Github\spendfy-microservices\account\node_modules\awilix\lib\container.js:207:51)
    at RouteRegister (P:\Coobo\Github\spendfy-microservices\account\src\routes.js:14:19)
    at Object.resolve (P:\Coobo\Github\spendfy-microservices\account\node_modules\awilix\lib\resolvers.js:294:20)
    at Object.resolve (P:\Coobo\Github\spendfy-microservices\account\node_modules\awilix\lib\container.js:250:45)
    at Object.<anonymous> (P:\Coobo\Github\spendfy-microservices\account\src\container\index.js:15:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (P:\Coobo\Github\spendfy-microservices\account\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (P:\Coobo\Github\spendfy-microservices\account\node_modules\pirates\lib\index.js:104:7)  
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (P:\Coobo\Github\spendfy-microservices\account\src\setup.js:1:127)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

But if I access it through the registrations property, it works
```js
Container.registrations.AccountIndexValidator.resolve(Container);
```
Outputs no Error

Am I missing something or is this a bug?

```
Node Version: 10.16.3
Awilix Version: 4.2.2
```

**Comment by VIMGAS** [comment]
Sure, this is how i access the container:

First of all, the Container is registered asValue inside the Container itself.

```js
-- file container.js

const _container = createContainer();
_container.register({ Container: asValue(_container) });
_container.register({ validate: asFunction(validate).singleton() });
```

In the app boot process, the container registers a routes.js file that looks like this:
```js
--- file routes.js

export default function RouteRegister({
  controller,
  validate,
  Server,
}) {
  const router = Server.openRouter();

  router
    .route('/accounts')
    .get(
      validate(
        'query',
        'AccountIndexValidator',
      ),
      controller('Account').index,
    )
    .post(
      validate('body', 'AccountStoreValidator'),
      controller('Account').store,
    );

  Server.useRouter('/', router);

  return router;
}
```

And the validate helper function looks like this:
```js
--- file validate.js

export default ({ ValidatorMiddleware, Container }) => {
  return function validate(type, schemaOrSchemaName) {
    const schema =
      typeof schemaOrSchemaName === 'string'
        ? Container.resolve(schemaOrSchemaName)
        : schemaOrSchemaName;

    if (!schema.validate || typeof schema.validate !== 'function')
      throw new Error('The provided schema is not valid.');

    return ValidatorMiddleware(type, schema);
  };
};
```

When the routes.js invokes the validate function, it passes the schemaName as a parameter : 'AccountIndexValidator' and the validate function is suposed to resolve it from the Container.

If I `console.log(Container)` on routes.js this is what I get:
```js
[AwilixContainer (registrations: 31)]
```

If I `console.log(Container.has('AccountIndexValidator'))` on routes.js this is what I get:
```js
true
```

If I invoke `Container.resolve('AccountIndexValidator')` on routes.js this is what I get:
```js
TypeError: Cannot read property 'AccountIndexValidator' of null
    at Object.resolve (P:\Coobo\Github\spendfy-microservices\account\node_modules\awilix\lib\container.js:207:51)
    at RouteRegister (P:\Coobo\Github\spendfy-microservices\account\src\routes.js:9:25)
    at Object.resolve (P:\Coobo\Github\spendfy-microservices\account\node_modules\awilix\lib\resolvers.js:294:20)
    at Object.resolve (P:\Coobo\Github\spendfy-microservices\account\node_modules\awilix\lib\container.js:250:45)
    at Object.<anonymous> (P:\Coobo\Github\spendfy-microservices\account\src\container\index.js:17:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (P:\Coobo\Github\spendfy-microservices\account\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (P:\Coobo\Github\spendfy-microservices\account\node_modules\pirates\lib\index.js:104:7)  
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (P:\Coobo\Github\spendfy-microservices\account\src\setup.js:1:127)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

But, if I do this:
```js
Container.registrations.Container.resolve(Container);
```
And Then call resolve:
```js
Container.resolve('AccountIndexValidator')
or
validate('query', 'AccountIndexValidator')
```
It works, don't exactly know why...

**Comment by jeffijoe** [comment]
We can't troubleshoot this without a full repro. @JamieCorkhill tried to reproduce it but was unable to.

**Comment by VIMGAS** [comment]
@jeffijoe @JamieCorkhill Allright, I put together a repo with the issue:

This is the repository where the issue occurs: https://github.com/VIMGAS/awilix-error-reference

This is the repository that corresponds for `@coobo/base` dependency (where the container is created): https://github.com/Coobo/microservice-base

To run into the issue all you need to do is:
```sh
yarn install
yarn dev
```

**Comment by jeffijoe** [comment]
You are registering literally everything in the container, like `asFunction` and `asClass`. This is not intended usage, I think you are overcomplicating things.

**Comment by VIMGAS** [comment]
My idea was using awilix as a depedency resolution for the entire application, it shouldn't be used like that?

**Comment by jeffijoe** [comment]
You should only inject things that you would either want to:

* Mock during testing (use sparingly)
* Be able to switch implementation later
* Have multiple implementations of the same interface

Injecting every single function is overkill. [See this boilerplate](http://github.com/jeffijoe/koa-es7-boilerplate) for an example.

**Comment by VIMGAS** [comment]
Ohh ok then... I thought I it would be ok to use it as a PHP's Laravel or adonisjs/fold kind of ioc container but without the provider classes.

**Comment by JamieCorkhill** [comment]
Your `Env` class is throwing an error that an env file is missing when I try to run `yarn dev`. I've also had to move the `--inspect` switch from `nodemon.json`. 

Also, this is not really a "minimal" reproduction - which is fine and I'm happy to help, but the more extraneous code that has nothing to do with the issue at hand that you can remove, the easier it is to pinpoint the exact reasons for the issue you're experiencing and rectify it.

If you intentionally didn't include the env file because it contains API Keys, tokens, or secrets, then I suppose that ties into my paragraph above.

**Comment by VIMGAS** [comment]
Ok @JamieCorkhill I have reduced the code amount to the minimum in order for the error repository to comply with the @coobo/base package and have already pushed it to the repo.

Is it better now? While you don't respond, I will keep trying to reproduce the error outside of the @coobo/base package scope.

**Comment by JamieCorkhill** [comment]
Thanks. I'm seeing your error now. I'll get back to you.

**Comment by jeffijoe** [comment]
You seem to be calling `register` inside of a constructor or factory function which is messing with Awilix' internal resolution stack tracker. What you are doing is not supported, and I would strongly recommend you rethink your architecture.

Thank you @JamieCorkhill for spending pretty much your whole day on this!

**Comment by JamieCorkhill** [comment]
You're welcome @jeffijoe and I'm happy to help.

Good luck with your architecture @VIMGAS. Take a look at `routes`, `Server`, `LoggerMiddleware`, and `LoggerClass` as @jeffijoe suggested. You might find that your issue exists there.

**Comment by VIMGAS** [comment]
@JamieCorkhill @jeffijoe Thank you both very much!

@JamieCorkhill sorry for making you spend so much time on this issue...

 I will take a deeper look at Awilix code and see if I could find a way to make it an available functionality with backwards compatibilty. As of now I only think of perhaps providing the root container as a second argument when dealing with PROXY injections, so code like:
```js
class NeedsDeps {
  constructor({ injectedDep }, container) {
    ...code...
  }
}
```
would be possible and the provided container would register new dependencies to the top of the stack tracker.

If that is an acceptable change for you in the package I would be happy to help with that.

Thanks again!

**Comment by jeffijoe** [comment]
Sorry, but I don't want to add support for this because this is a mis-use of the package. Again, I would suggest you take a look at the boilerplate I linked above. 😃

**Comment by VIMGAS** [comment]
Aboslutely no problem @jeffijoe ! Thank you very much again!
