### ISSUE TITLE
Getting AwilixResolutionError, Best practice to resolve circular dependencies?

### ISSUE THREAD

**Issue by BartaG512** [jeffijoe/awilix#171]
I am trying to resolve two modules and i get `AwilixResolutionError`. 
I was able to fix this by adding getters, and not destructing in constructor, My examples are below.
But i guess my solution is not the best way to do this.
How is awilix is intended to be used for this problem?

```
AwilixResolutionError: Could not resolve 'controller'. Cyclic dependencies detected.

Resolution path: controller -> interfaceApi -> controller
    at resolve (C:\di-test\node_modules\awilix\lib\container.js:209:23)
    at Object.get (C:\di-test\node_modules\awilix\lib\container.js:65:32)
    at new InterfaceApi (C:\di-test\modules\interface-api\interface-api.js:25:16)
    at newClass (C:\di-test\node_modules\awilix\lib\resolvers.js:85:24)
    at Object.resolve (C:\di-test\node_modules\awilix\lib\resolvers.js:294:20)
    at resolve (C:\di-test\node_modules\awilix\lib\container.js:254:45)
    at Object.get (C:\di-test\node_modules\awilix\lib\container.js:65:32)
    at new Controller (C:\di-test\modules\controller\controller.js:3:16)
    at newClass (C:\di-test\node_modules\awilix\lib\resolvers.js:85:24)
    at Object.resolve (C:\di-test\node_modules\awilix\lib\resolvers.js:294:20)
```

My implemenetation: 

```js
// controller.js
class Controller {
	constructor({ interfaceApi }) {
		this.interfaceApi = interfaceApi;
	}

	sendMessage() {
		this.interfaceApi.messageSender.send({
			type: 'B',
			payload: 'content',
		});
	}

	handleA() {
		console.log('A type message handled');
	}
}

module.exports = Controller;
```

```js 
// interface-api.js
class MessageSender {
	constructor({ interfaceApi }) {
		this.interfaceApi = interfaceApi;
	}

	send() {
		console.log('send message');
	}
}

class MessageHandler {
	constructor({ interfaceApi }) {
		this.interfaceApi = interfaceApi;
	}

	handleMessage(message) {
		if (message.type === 'A') {
			this.interfaceApi.controller.handleA(message.payload);
		}
	}
}

class InterfaceApi {
	constructor({ controller }) {
		this.controller = controller;
		this.messageSender = new MessageSender({ interfaceApi: this });
		this.messageHandler = new MessageHandler({ interfaceApi: this });
	}
}

module.exports = InterfaceApi;
```
In my index.js file i do this

```js
'use strict';
const {
	createContainer,
	InjectionMode,
	Lifetime,
} = require('awilix');

const container = createContainer();
container.loadModules(['modules/**/*.js'], {
	formatName: 'camelCase',
	resolverOptions: {
		injectionMode: InjectionMode.PROXY,
		lifetime: Lifetime.SINGLETON,
	},
});

const controller = container.resolve('controller');
const interfaceApi = container.resolve('interfaceApi');
controller.sendMessage();
interfaceApi.messageHandler.handleMessage({
	type: 'A',
	payload: 'content',
});
```

I was able to fix this by getters: 

```js
// interface-api.js
class InterfaceApi {
	constructor(proxy) {
		this.proxy = proxy;
		this.messageSender = new MessageSender({ interfaceApi: this });
		this.messageHandler = new MessageHandler({ interfaceApi: this });
	}

	get controller() {
		return this.proxy.controller;
	}
}
```

```js
// controller.js
class Controller {
	constructor(proxy) {
		this.proxy = proxy;
	}

	get interfaceApi() {
		return this.proxy.interfaceApi;
	}

	sendMessage() {
		this.interfaceApi.messageSender.send({
			type: 'B',
			payload: 'content',
		});
	}

	handleA() {
		console.log('"A" type message handled');
	}
}

module.exports = Controller;
```

**Comment by jeffijoe** [comment]
Maybe rethink your dependency graph? It's usually a sign that something is wrong with the design.

Alternatively, use a lazy getter, so register a `getInterfaceApi` that just lazy-resolves on invoke:

```ts
import { once } from 'lodash'

container.register({
  getInterfaceApi: {
    resolve: c => once(() => c.resolve('interfaceApi'))
  }
})
```

Then any time you need `interfaceApi` you just call that function. Its not pretty but it highlights a bigger problem in your design.

**Comment by BartaG512** [comment]
So the problem maybe that i wrapped 2 class into 1. If I would split these to into separate modules, like CncomingApi, and OutgoingApi, then controller would need outgoingApi only to send requests, and incomingApi would only needs controller to call handler functions. And probably i would cut the circular dependency.
