### ISSUE TITLE
Required package: jest-config (via "jest-config/build")

### ISSUE THREAD

**Issue by moltar** [jeffijoe/awilix#180]
Running `yarn test` results in the following:

```
 FAIL  src/__tests__/param-parser.bugs.test.ts
  ● Test suite failed to run

    A package is trying to access another package without the second one being listed as a dependency of the first one

    Required package: jest-config (via "jest-config/build")
    Required by: ts-jest@virtual:fb40d9125d9933ab66c06cfcf0247ffb37f2bf7b8608a323290861de8925f0261a323aaccdeecf25c486bce119bc3ebb7f645cfc3a2465af485bf89f78c2db3c#npm:25.2.1 (via ~/pkg/awilix/.yarn/$$virtual/ts-jest-virtual-546aad75ef/0/cache/ts-jest-npm-25.2.1-abe6e4496f-1.zip/node_modules/ts-jest/dist/)

    Require stack:
    - ~/pkg/awilix/.yarn/$$virtual/ts-jest-virtual-546aad75ef/0/cache/ts-jest-npm-25.2.1-abe6e4496f-1.zip/node_modules/ts-jest/dist/compiler.js
    - ~/pkg/awilix/.yarn/$$virtual/ts-jest-virtual-546aad75ef/0/cache/ts-jest-npm-25.2.1-abe6e4496f-1.zip/node_modules/ts-jest/dist/config/config-set.js
    - ~/pkg/awilix/.yarn/$$virtual/ts-jest-virtual-546aad75ef/0/cache/ts-jest-npm-25.2.1-abe6e4496f-1.zip/node_modules/ts-jest/dist/ts-jest-transformer.js
    - ~/pkg/awilix/.yarn/$$virtual/ts-jest-virtual-546aad75ef/0/cache/ts-jest-npm-25.2.1-abe6e4496f-1.zip/node_modules/ts-jest/dist/index.js
    - ~/pkg/awilix/.yarn/cache/@jest-transform-npm-25.1.0-5f5645c4ef-1.zip/node_modules/@jest/transform/build/ScriptTransformer.js
    - ~/pkg/awilix/.yarn/cache/@jest-transform-npm-25.1.0-5f5645c4ef-1.zip/node_modules/@jest/transform/build/index.js
    - ~/pkg/awilix/.yarn/cache/jest-runtime-npm-25.1.0-9a183c5bd3-1.zip/node_modules/jest-runtime/build/index.js
    - ~/pkg/awilix/.yarn/cache/jest-runner-npm-25.1.0-b6783ee1c8-1.zip/node_modules/jest-runner/build/testWorker.js
    - ~/pkg/awilix/.yarn/cache/jest-worker-npm-25.1.0-3e76b6b8a3-1.zip/node_modules/jest-worker/build/workers/processChild.js

      13882 | function makeError(pnpCode, message, data = {}) {
      13883 |   const code = MODULE_NOT_FOUND_ERRORS.has(pnpCode) ? `MODULE_NOT_FOUND` : pnpCode;
    > 13884 |   return Object.assign(new Error(message), {
            |                        ^
      13885 |     code,
      13886 |     pnpCode,
      13887 |     data

      at Object.makeError (.pnp.js:13884:24)
      at resolveToUnqualified (.pnp.js:22747:35)
      at resolveRequest (.pnp.js:22824:27)
      at Object.resolveRequest (.pnp.js:22892:26)
      at Function.module_1.Module._resolveFilename (.pnp.js:22122:34)
      at Function.module_1.Module._load (.pnp.js:22007:40)
```

**Comment by moltar** [comment]
Installing `jest-config` as global does not fix the problem.

**Comment by moltar** [comment]
After `yarn add jest-config`, I get a set of new errors:

 FAIL  src/__tests__/inheritance.test.js
  ● Test suite failed to run

    Cannot find module '@babel/plugin-transform-runtime' from '~/pkg/awilix'

**Comment by jeffijoe** [comment]
Seems to be a yarn pnp problem. Try just using npm.
