### ISSUE TITLE
Can not resolve via Symbol()

### ISSUE THREAD

**Issue by sarneeh** [jeffijoe/awilix#317]
Although the `register/resolve` [documentation](https://github.com/jeffijoe/awilix#containerregister) does not say anything about supporting `Symbol`, the [register](https://github.com/jeffijoe/awilix/blob/master/src/container.ts#L69) and [resolve](https://github.com/jeffijoe/awilix/blob/master/src/container.ts#LL96) definitions do suggest that a symbol can be used and should be working.

Unfortunately it does not.

Here's a quick reproduction:
```js
const { asClass, createContainer, InjectionMode } = require('awilix');

const container = createContainer();

class A {
  static SYMBOL = Symbol('a');
  constructor({ b }) {
    console.log(b);
  }
}

class B {
  static SYMBOL = Symbol('b');
  constructor() {}
}

container.register(A.SYMBOL, asClass(A));
container.register(B.SYMBOL, asClass(B));

const a = container.resolve(A.SYMBOL);

console.log(a);
```

The script above results in:
```
AwilixResolutionError: Could not resolve 'b'.

Resolution path: Symbol(a) -> b
    at resolve (file:///home/projects/node-8nub6z/node_modules/awilix/lib/container.js:252:23)
    at Object.get (file:///home/projects/node-8nub6z/node_modules/awilix/lib/container.js:66:33)
    at new A (file:///home/projects/node-8nub6z/index.js:7:17)
    at newClass (file:///home/projects/node-8nub6z/node_modules/awilix/lib/resolvers.js:86:24)
    at Object.resolve (file:///home/projects/node-8nub6z/node_modules/awilix/lib/resolvers.js:295:20)
    at Object.resolve (file:///home/projects/node-8nub6z/node_modules/awilix/lib/container.js:262:41)
    at Object.eval (file:///home/projects/node-8nub6z/index.js:20:21)
    at Object.function (https://node8nub6z-siia.w-credentialless.staticblitz.com/blitz.88d3a49b591611919d7d64c44b90ff5f8e939906.js:15:144744)
    at Module._compile (https://node8nub6z-siia.w-credentialless.staticblitz.com/blitz.88d3a49b591611919d7d64c44b90ff5f8e939906.js:6:244076)
    at Module._extensions..js (https://node8nub6z-siia.w-credentialless.staticblitz.com/blitz.88d3a49b591611919d7d64c44b90ff5f8e939906.js:6:244741)
```

And a [StackBlitz](https://stackblitz.com/edit/node-8nub6z?file=index.js), for convenience.

**Comment by jeffijoe** [comment]
That's because `{ b }` will use the string key to resolve. How would you expect Awilix to know what symbol to use?

If you change your deconstruction to alias the symbol, then it'll work.

```js
class A {
  static SYMBOL = Symbol('a');
  constructor({ [B.SYMBOL]: b }) {
    console.log(b);
  }
}
```
