### ISSUE TITLE
Class returning undefined when attempting to register

### ISSUE THREAD

**Issue by Beardles** [jeffijoe/awilix#79]
I have multiple classes registered on my container, and all has been working flawlessly so far.  However, I have one class that returns the following error when attempting to register it as a class:

`AwilixTypeError: asClass: expected Type to be class, but got undefined.`

I cannot for the life of me figure out why this class is returning this error -- I've read through the docs multiple times and didnt spot anything -- perhaps I am missing something?

Here's the class:
```
export default class ServerConfig {
  _app;

  constructor({ logger, uploadsController }) {
    this._app = express();
    this.logger = logger;
    this.uploadsController = uploadsController;
    this.initGraphql();
    this.initGraphiql();
    this.initUploads();
  }

  get app() {
    return this._app;
  }

  initGraphql() {
    // implementation
  }

  initGraphiql() {
    // implementation
  }

  initUploads() {
    // implementation
  }
}
```

Here's my container setup:
```
const container = createContainer();

container.register({
  logger: asValue(logger),
  salesforceClient: asValue(salesforceGeneral),

  s3client: asClass(S3, { lifetime: Lifetime.SINGLETON }),
  uploadsController: asClass(UploadsController, { lifetime: Lifetime.SINGLETON }),

  caseResolver: asClass(CaseResolver, { lifetime: Lifetime.SINGLETON }),
  commentResolver: asClass(CommentResolver, { lifetime: Lifetime.SINGLETON }),
  uploadResolver: asClass(UploadResolver, { lifetime: Lifetime.SINGLETON }),

  salesforceService: asClass(SalesforceService, { lifetime: Lifetime.SINGLETON }),
  s3Service: asClass(S3Service, { lifetime: Lifetime.SINGLETON }),

  serverConfig: asClass(ServerConfig, { lifetime: Lifetime.SINGLETON }),
});
```

Again, all of the other classes and values are resolved fine, it is strictly an issue with `ServerConfig`. Please let me know if I can provide any additional information.

**Comment by jeffijoe** [comment]
How are you importing it?

**Comment by Beardles** [comment]
Here's my import list:

```
import { createContainer, asValue, asClass, Lifetime } from 'awilix';
import logger from './logger';
import salesforceGeneral from './salesforce';
import CaseResolver from '../resolver/case.resolver';
import SalesforceService from '../service/salesforce.service';
import CommentResolver from '../resolver/comment.resolver';
import S3 from './aws';
import UploadResolver from '../resolver/upload.resolver';
import S3Service from '../service/s3.service';
import UploadsController from './uploads';
import ServerConfig from './express';
```

**Comment by jeffijoe** [comment]
Could you attach a stack trace of when the error occurs?

**Comment by Beardles** [comment]
Sure thing, here you go:

```
error: uncaughtException: asClass: expected Type to be class, but got undefined. date=Fri Feb 09 2018 10:16:37 GMT-0600 (CST), pid=45900, uid=501, gid=20, cwd=PATH_TO_PROJECT, execPath=/usr/local/Cellar/node/8.9.1/bin/node, version=v8.9.1, argv=[node, PATH_TO_PROJECT/server/server.js], rss=121040896, heapTotal=92524544, heapUsed=71409440, external=18007532, loadavg=[4.3544921875, 4.42236328125, 4.2763671875], uptime=3258946
AwilixTypeError: asClass: expected Type to be class, but got undefined.
    at asClass (PATH_TO_PROJECT/node_modules/awilix/src/resolvers.ts:189:11)
    at Object.<anonymous> (PATH_TO_PROJECT/server/lib/container.js:29:17)
    at Module._compile (module.js:635:30)
    at loader (PATH_TO_PROJECT/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (PATH_TO_PROJECT/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
```

**Comment by jeffijoe** [comment]
Hmm, so this only happens when you run `asClass(ServerConfig)`? What gets printed if you do `console.log(ServerConfig)`?

**Comment by Beardles** [comment]
It just prints `undefined` so perhaps this isn't an issue with the library then...

The only other thing that is tripping me up is that in my server file I can do this just fine:

```
import ServerConfig from './lib/express';
import container from './lib/container';

require('dotenv').config();

const config = require('../config/default.json');

const logger = container.resolve('logger');
const uploadsController = container.resolve('uploadsController');

const serverConfig = new ServerConfig(({ logger, uploadsController }));
const { app } = serverConfig;
```

This is working, but I would like to resolve things properly in the container.

**Comment by jeffijoe** [comment]
Yeah I get that.

In your case though, I would use `container.build`:

```js
const serverConfig = container.build(asClass(ServerConfig))
const { app } = serverConfig;
```

I don't know enough about your setup to help with that other anomaly though. I think it's safe to say it's not related to Awilix. 😄

**Comment by Beardles** [comment]
Yep, I would agree -- thanks for helping me rule it out (and thanks for the awesome library!).

**Comment by jeffijoe** [comment]
You're welcome. Good luck!

**Comment by johnmalatras** [comment]
@Beardles did you ever resolve this? Running into the same issue.

**Comment by alfredwurr** [comment]
For me, importing the container in a class file that also gets registered in the container caused it.
E.g. Having import { container } from '../container'; in the file that defines a class that's itself registered in the container.
